site_name: SEFGH-AI Docs
site_url: https://docs.sefgh.org/
nav:
  - Home: index.md

theme:
  name: material  # or 'readthedocs' or other supported themes

markdown_extensions:
  - toc:
      permalink: true

# Optional - If your docs are not in the root directory
docs_dir: docs
