site_name: SEFGH-AI Docs
site_url: https://docs.sefgh.org/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Search Engine Architecture: architecture.md
  - Customization Guide: customization.md
  - API Reference: api-reference.md

theme:
  name: material  # or 'readthedocs' or other supported themes

markdown_extensions:
  - toc:
      permalink: true

# Optional - If your docs are not in the root directory
docs_dir: docs
